version: "3.8"

services:
  backend:
      container_name: toro_backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      user: $USER
      command: npm run start:dev
      ports:
        - 3000:3000
      volumes:
        - ./backend:/app
