import Head from 'next/head';
import Layout from '@/shared/layout';
import { Box, Typography, Container } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Container>
            <Box
              display="flex"
              flexDirection="column"
              alignItems="center"
              justifyContent="center"
              mt={10}
            >
              <Typography variant="h1" align="center">
                Welcome to Toro!
              </Typography>
              <Typography>Please login to access your account.</Typography>
            </Box>
          </Container>
        </Layout>
      </main>
    </>
  );
}
